/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.view;

/**
 *
 * @author Arber
 */
public class Detajet extends javax.swing.JInternalFrame {

    /**
     * Creates new form Detajet
     */
    public Detajet() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lSektori = new javax.swing.JLabel();
        lShteti = new javax.swing.JLabel();
        lQyteti = new javax.swing.JLabel();
        lRuga = new javax.swing.JLabel();
        lEmri = new javax.swing.JLabel();
        lNumriShpis = new javax.swing.JLabel();
        lMbiemri = new javax.swing.JLabel();
        lGjinia = new javax.swing.JLabel();
        lDataLindjes = new javax.swing.JLabel();
        lFjalkalimi = new javax.swing.JLabel();
        lSpecializimi = new javax.swing.JLabel();
        lDetajetTjera = new javax.swing.JLabel();

        setClosable(true);

        lSektori.setText("Sektori        -------------->");
        lSektori.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lSektoriAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        lShteti.setText("Shteti          -------------->");
        lShteti.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lShtetiAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        lQyteti.setText("Qyteti         -------------->");
        lQyteti.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lQytetiAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        lRuga.setText("Ruga           -------------->");
        lRuga.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lRugaAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        lEmri.setText("Emri              -------------->");
        lEmri.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lEmriAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        lNumriShpis.setText("Nr               -------------->");
        lNumriShpis.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lNumriShpisAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        lMbiemri.setText("Mbiemri        -------------->");
        lMbiemri.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lMbiemriAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        lGjinia.setText("Gjinia           -------------->");
        lGjinia.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lGjiniaAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        lDataLindjes.setText("Data lindjes -------------->");
        lDataLindjes.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lDataLindjesAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        lFjalkalimi.setText("Fjalkalimi     -------------->");
        lFjalkalimi.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lFjalkalimiAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        lSpecializimi.setText("Specializimi  -------------->");
        lSpecializimi.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lSpecializimiAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        lDetajetTjera.setText("Detajet tjera------------>");
        lDetajetTjera.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lDetajetTjeraAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lDetajetTjera, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lSektori, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(164, 164, 164))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lEmri, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                            .addComponent(lMbiemri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lGjinia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lDataLindjes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lShteti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lQyteti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lRuga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lNumriShpis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lFjalkalimi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lSpecializimi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(lEmri)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lMbiemri)
                .addGap(13, 13, 13)
                .addComponent(lGjinia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lDataLindjes)
                .addGap(11, 11, 11)
                .addComponent(lShteti)
                .addGap(11, 11, 11)
                .addComponent(lQyteti)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lRuga)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lNumriShpis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lFjalkalimi, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(lSpecializimi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lSektori)
                .addGap(18, 18, 18)
                .addComponent(lDetajetTjera)
                .addContainerGap(53, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lEmriAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lEmriAncestorAdded
        lEmri.setText("Emri              -------------->"+FshijForma.emri);
    }//GEN-LAST:event_lEmriAncestorAdded

    private void lMbiemriAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lMbiemriAncestorAdded
        lMbiemri.setText("Mbiemri        -------------->"+FshijForma.mbiemri);
    }//GEN-LAST:event_lMbiemriAncestorAdded

    private void lGjiniaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lGjiniaAncestorAdded
        lGjinia.setText("Gjinia           -------------->"+FshijForma.gjinia);
    }//GEN-LAST:event_lGjiniaAncestorAdded

    private void lDataLindjesAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lDataLindjesAncestorAdded
       lDataLindjes.setText("Data lindjes -------------->"+FshijForma.dataLindjes);
    }//GEN-LAST:event_lDataLindjesAncestorAdded

    private void lShtetiAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lShtetiAncestorAdded
        lShteti.setText("Shteti          -------------->"+FshijForma.shteti);
    }//GEN-LAST:event_lShtetiAncestorAdded

    private void lQytetiAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lQytetiAncestorAdded
        lQyteti.setText("Qyteti         -------------->"+FshijForma.qyteti);
    }//GEN-LAST:event_lQytetiAncestorAdded

    private void lRugaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lRugaAncestorAdded
        lRuga.setText("Ruga           -------------->"+FshijForma.ruga);
    }//GEN-LAST:event_lRugaAncestorAdded

    private void lNumriShpisAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lNumriShpisAncestorAdded
        lNumriShpis.setText("Nr               -------------->"+FshijForma.numri);
    }//GEN-LAST:event_lNumriShpisAncestorAdded

    private void lFjalkalimiAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lFjalkalimiAncestorAdded
        lFjalkalimi.setText("Fjalkalimi     -------------->"+FshijForma.fjalkalimi);
    }//GEN-LAST:event_lFjalkalimiAncestorAdded

    private void lSpecializimiAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lSpecializimiAncestorAdded
        lSpecializimi.setText("Specializimi  -------------->"+FshijForma.specjalizimi);
    }//GEN-LAST:event_lSpecializimiAncestorAdded

    private void lSektoriAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lSektoriAncestorAdded
        lSektori.setText("Sektori        -------------->"+FshijForma.sektori);
    }//GEN-LAST:event_lSektoriAncestorAdded

    private void lDetajetTjeraAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lDetajetTjeraAncestorAdded
        lDetajetTjera.setText("Detajet tjera------------>"+FshijForma.detajetTjera);
    }//GEN-LAST:event_lDetajetTjeraAncestorAdded


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lDataLindjes;
    private javax.swing.JLabel lDetajetTjera;
    private javax.swing.JLabel lEmri;
    private javax.swing.JLabel lFjalkalimi;
    private javax.swing.JLabel lGjinia;
    private javax.swing.JLabel lMbiemri;
    private javax.swing.JLabel lNumriShpis;
    private javax.swing.JLabel lQyteti;
    private javax.swing.JLabel lRuga;
    private javax.swing.JLabel lSektori;
    private javax.swing.JLabel lShteti;
    private javax.swing.JLabel lSpecializimi;
    // End of variables declaration//GEN-END:variables
}
