/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.view;

import BL.DhomaRepository;
import EJB.Dhoma;
import GUI.model.DhomaTableModel;
import Main.SpitaliGUI;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Arber
 */
public class DhomaMForma extends javax.swing.JInternalFrame {

    private DhomaTableModel dtm = new DhomaTableModel();
    private DhomaRepository dr = new DhomaRepository();
    public static Dhoma d = null;
    
   /* private Connection con = null;
    private PreparedStatement ps = null;
    private ResultSet rs = null;*/
    
    public DhomaMForma() {
        initComponents();
        initTeble();
        jComboBoxSektori.setVisible(false);
        jLabel1.setVisible(false);
        /*try {
            con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=SpitaliDB1_2;user=sa;password=arber;");
        } catch (SQLException ex) {
            Logger.getLogger(Test.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDhomat = new javax.swing.JTable();
        jComboBoxSektori = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setClosable(true);

        jTableDhomat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableDhomat);

        jComboBoxSektori.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1.Kirurgji" }));
        jComboBoxSektori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSektoriActionPerformed(evt);
            }
        });

        jLabel1.setText("Sektori:");

        jButton1.setText("Shto Pacient");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxSektori, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 716, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxSektori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void initTeble()
    {
        List<Dhoma> list = dr.findAll();
        dtm.add(list);
        jTableDhomat.setModel(dtm);
        dtm.fireTableDataChanged();
    }
    
   /* public void initTeble(List<Dhoma> list)
    {
        dtm.add(list);
        jTableDhomat.setModel(dtm);
        dtm.fireTableDataChanged();
    }*/
    
    private void jComboBoxSektoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSektoriActionPerformed
        /*String x = jComboBoxSektori.getSelectedItem().toString();
        String [] y = x.split("\\.");
        
        String q = "Select * FROM Dhoma d where d.sektori_ID = '"+1+"'";
        try
        {
            ps = con.prepareStatement(q);
            
            rs = ps.executeQuery();
            jTableDhomat.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(SQLException e){}
        
        /*int i = Integer.parseInt(y[0]);
        Sektori s = new Sektori();
        s.setId(Integer.parseInt(y[0]));
        s.setEmri(y[1]);
        System.out.println(i);
        initTeble(dr.findBySektori(i));*/
    }//GEN-LAST:event_jComboBoxSektoriActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        int x = jTableDhomat.getSelectedRow();
        
        if(x>-1)
        {
            d = dtm.getDhoma(x);
            ShtoPacientinDH s = new ShtoPacientinDH();
            SpitaliGUI.desktopPane.add(s);
            s.show();
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Nuk keni selektuar asni Dhomë");
        }
        
        /*TableModel tm = jTableDhomat.getModel();
        int [] reshtat = jTableDhomat.getSelectedRows();
        //DefaultTableModel d = (DefaultTableModel) jTable1.getModel();
       // d =(Dhoma) tm.getValueAt(reshtat,0);
        
        Object [] v = new Object[5];
        
        for(int i=0;i<reshtat.length;i++)
        {
            v[0] = tm.getValueAt(reshtat[i],0);
            v[1] = tm.getValueAt(reshtat[i],1);
            v[2] = tm.getValueAt(reshtat[i], 2);
            v[3] = tm.getValueAt(reshtat[i], 3);
            v[4] = tm.getValueAt(reshtat[i], 4);
            
            //d.addRow(v);
        }
        d.setId(Integer.parseInt(v[0].toString()));
        d.setNrdhomes(Integer.parseInt(v[1].toString()));
        d.setNrshtratve(Integer.parseInt(v[2].toString()));
        d.setCountP(Integer.parseInt(v[3].toString()));
        d.setSektoriID((Sektori)v[4]);
        System.out.println(d.getSektoriID());
        /*Dhoma d = dtm.getDhoma(jTableDhomat.getSelectedRow());
        
        System.out.println(d.getId());*/
    }//GEN-LAST:event_jButton1ActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBoxSektori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDhomat;
    // End of variables declaration//GEN-END:variables
}
