/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.view;

import EJB.Sektori;
import javax.swing.JOptionPane;

/**
 *
 * @author Arber
 */
public class EditDhoma extends javax.swing.JInternalFrame {

    /**
     * Creates new form EditDhoma
     */
    public EditDhoma() {
        initComponents();
        initInformatat();
    }

    public void initInformatat()
    {
        txtNrDhomes.setText(String.valueOf(DhomaForma.d.getNrdhomes()));
        txtNrShtratave.setText(String.valueOf(DhomaForma.d.getNrshtratve()));
        jComboBoxSektori.setSelectedItem(DhomaForma.d.getSektoriID().getEmri());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNrDhomes = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNrShtratave = new javax.swing.JTextField();
        jComboBoxSektori = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setClosable(true);

        jLabel1.setText("Numri i dhomes");

        txtNrDhomes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNrDhomesActionPerformed(evt);
            }
        });

        jLabel2.setText("Numri i shtratve");

        jComboBoxSektori.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sektori", "1.Kirurgjisë" }));

        jLabel4.setText("Sektori");

        jButton1.setText("Edito");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtNrShtratave)
                        .addComponent(txtNrDhomes, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBoxSektori, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNrDhomes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNrShtratave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBoxSektori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(51, 51, 51)
                .addComponent(jButton1)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNrDhomesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNrDhomesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNrDhomesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        if(txtNrDhomes.getText()!="" && txtNrShtratave.getText()!="")
        {
            DhomaForma.d.setNrdhomes(Integer.parseInt(txtNrDhomes.getText()));
            DhomaForma.d.setNrshtratve(Integer.parseInt(txtNrShtratave.getText()));
       
            String x = jComboBoxSektori.getSelectedItem().toString();
            String [] y = x.split("\\.");
            Sektori s = new Sektori();
            s.setEmri(y[1]);
            s.setId(Integer.parseInt(y[0]));
            DhomaForma.d.setSektoriID(s);
        }
        else
        {
            JOptionPane.showMessageDialog(null, "");
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBoxSektori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtNrDhomes;
    private javax.swing.JTextField txtNrShtratave;
    // End of variables declaration//GEN-END:variables
}
