/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.view;

import BL.DoktoriRepository;
import BL.InfermieriRepository;
import BL.RescepsionistiRepository;
import BL.SpitaliException;
import EJB.Doktori;
import EJB.Motra;
import EJB.Rescepsionisti;
import GUI.model.DoktoriTableModel;
import GUI.model.InfermieriTableModel;
import GUI.model.RecepsionistiTebleModel;
import Main.SpitaliGUI;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Arber
 */
public class Search extends javax.swing.JInternalFrame {

    private DoktoriRepository dr = new DoktoriRepository();
    private DoktoriTableModel dtm = new DoktoriTableModel();
    private RescepsionistiRepository rr = new RescepsionistiRepository();
    private RecepsionistiTebleModel rtm = new RecepsionistiTebleModel();
    private InfermieriRepository ir = new InfermieriRepository();
    private InfermieriTableModel itm = new InfermieriTableModel();
    public static Rescepsionisti r = null;
    public static Doktori d = null;
    public static Motra m = null;
    
    public Search() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
    */
    
    public void fillTableD(List<Doktori> list)
    {
        dtm.add(list);
        DoktorijTable.setModel(dtm);
        dtm.fireTableDataChanged();
    }
    
    public void fillTableR(List<Rescepsionisti> list)
    {
        rtm.add(list);
        RecepsjonistijTable.setModel(rtm);
        rtm.fireTableDataChanged();
    }
    
    public void fillTableM(List<Motra> list)
    {
        itm.add(list);
        InfermjerijTable.setModel(itm);
        itm.fireTableDataChanged();
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DoktorijTable = new javax.swing.JTable();
        jRadioButtonId = new javax.swing.JRadioButton();
        jRadioButtonEmri = new javax.swing.JRadioButton();
        jRadioButtonMbiemri = new javax.swing.JRadioButton();
        jRadioButtonEmritMbiemrit = new javax.swing.JRadioButton();
        jTextD = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        RecepsjonistijTable = new javax.swing.JTable();
        jRadioButtonIdR = new javax.swing.JRadioButton();
        jRadioButtonEmriR = new javax.swing.JRadioButton();
        jRadioButtonMbiemriR = new javax.swing.JRadioButton();
        jRadioButtonEmritMbiemritR = new javax.swing.JRadioButton();
        jTextR = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jRadioButtonMbiemriM = new javax.swing.JRadioButton();
        jRadioButtonEmritMbiemritM = new javax.swing.JRadioButton();
        jTextM = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        InfermjerijTable = new javax.swing.JTable();
        jRadioButtonIdM = new javax.swing.JRadioButton();
        jRadioButtonEmriM = new javax.swing.JRadioButton();

        setClosable(true);

        DoktorijTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(DoktorijTable);

        jRadioButtonId.setText("Kërko sipas ID");
        jRadioButtonId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonIdActionPerformed(evt);
            }
        });

        jRadioButtonEmri.setText("Kërko sipas emrit");
        jRadioButtonEmri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonEmriActionPerformed(evt);
            }
        });

        jRadioButtonMbiemri.setText("Kërko sipas mbiemrit");
        jRadioButtonMbiemri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMbiemriActionPerformed(evt);
            }
        });

        jRadioButtonEmritMbiemrit.setText("Kërko sipas emrit dhe mbiemrit");
        jRadioButtonEmritMbiemrit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonEmritMbiemritActionPerformed(evt);
            }
        });

        jTextD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDActionPerformed(evt);
            }
        });

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Edito");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setText("Fshij");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 958, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextD, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80)
                                .addComponent(jButton1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButtonId)
                                .addGap(63, 63, 63)
                                .addComponent(jRadioButtonEmri)
                                .addGap(69, 69, 69)
                                .addComponent(jRadioButtonMbiemri)
                                .addGap(64, 64, 64)
                                .addComponent(jRadioButtonEmritMbiemrit))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonId)
                    .addComponent(jRadioButtonEmri)
                    .addComponent(jRadioButtonMbiemri)
                    .addComponent(jRadioButtonEmritMbiemrit))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Search Doktorin", jPanel1);

        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setText("Edito");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Fshij");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        RecepsjonistijTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(RecepsjonistijTable);

        jRadioButtonIdR.setText("Kërko sipas ID");
        jRadioButtonIdR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonIdRActionPerformed(evt);
            }
        });

        jRadioButtonEmriR.setText("Kërko sipas emrit");
        jRadioButtonEmriR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonEmriRActionPerformed(evt);
            }
        });

        jRadioButtonMbiemriR.setText("Kërko sipas mbiemrit");
        jRadioButtonMbiemriR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMbiemriRActionPerformed(evt);
            }
        });

        jRadioButtonEmritMbiemritR.setText("Kërko sipas emrit dhe mbiemrit");
        jRadioButtonEmritMbiemritR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonEmritMbiemritRActionPerformed(evt);
            }
        });

        jTextR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 958, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTextR, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80)
                                .addComponent(jButton3))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jRadioButtonIdR)
                                .addGap(63, 63, 63)
                                .addComponent(jRadioButtonEmriR)
                                .addGap(69, 69, 69)
                                .addComponent(jRadioButtonMbiemriR)
                                .addGap(64, 64, 64)
                                .addComponent(jRadioButtonEmritMbiemritR))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonIdR)
                    .addComponent(jRadioButtonEmriR)
                    .addComponent(jRadioButtonMbiemriR)
                    .addComponent(jRadioButtonEmritMbiemritR))
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Search Recepsjonisti", jPanel2);

        jRadioButtonMbiemriM.setText("Kërko sipas mbiemrit");
        jRadioButtonMbiemriM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMbiemriMActionPerformed(evt);
            }
        });

        jRadioButtonEmritMbiemritM.setText("Kërko sipas emrit dhe mbiemrit");
        jRadioButtonEmritMbiemritM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonEmritMbiemritMActionPerformed(evt);
            }
        });

        jTextM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextMActionPerformed(evt);
            }
        });

        jButton7.setText("Search");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Edito");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Fshij");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        InfermjerijTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(InfermjerijTable);

        jRadioButtonIdM.setText("Kërko sipas ID");
        jRadioButtonIdM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonIdMActionPerformed(evt);
            }
        });

        jRadioButtonEmriM.setText("Kërko sipas emrit");
        jRadioButtonEmriM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonEmriMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 958, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jTextM, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80)
                                .addComponent(jButton7))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jRadioButtonIdM)
                                .addGap(63, 63, 63)
                                .addComponent(jRadioButtonEmriM)
                                .addGap(69, 69, 69)
                                .addComponent(jRadioButtonMbiemriM)
                                .addGap(64, 64, 64)
                                .addComponent(jRadioButtonEmritMbiemritM))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonIdM)
                    .addComponent(jRadioButtonEmriM)
                    .addComponent(jRadioButtonMbiemriM)
                    .addComponent(jRadioButtonEmritMbiemritM))
                .addGap(48, 48, 48)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("tab3", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1045, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jTabbedPane1)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 531, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(32, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonIdActionPerformed
        if(jRadioButtonId.isSelected())
        {
            jRadioButtonEmri.setSelected(false);
            jRadioButtonEmritMbiemrit.setSelected(false);
            jRadioButtonMbiemri.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButtonIdActionPerformed

    private void jRadioButtonMbiemriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMbiemriActionPerformed
        if(jRadioButtonMbiemri.isSelected())
        {
            jRadioButtonEmri.setSelected(false);
            jRadioButtonEmritMbiemrit.setSelected(false);
            jRadioButtonId.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButtonMbiemriActionPerformed

    private void jRadioButtonEmritMbiemritActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonEmritMbiemritActionPerformed
        if(jRadioButtonEmritMbiemrit.isSelected())
        {
            jRadioButtonEmri.setSelected(false);
            jRadioButtonMbiemri.setSelected(false);
            jRadioButtonId.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButtonEmritMbiemritActionPerformed

    private void jTextDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextDActionPerformed

    public void searchR(String x)
    {
        List<Rescepsionisti> list = null;
        
        if(jRadioButtonIdR.isSelected())
        {
                list = rr.findById(Integer.parseInt(jTextR.getText()));
                fillTableR(list);
        }
        else if(jRadioButtonEmriR.isSelected())
        {
                list = rr.findByEmri(jTextR.getText());
                fillTableR(list);
        }
        else if(jRadioButtonMbiemriR.isSelected())
        {
                list = rr.findByMbiemri(jTextR.getText());
                fillTableR(list);
        }
        else if(jRadioButtonEmritMbiemritR.isSelected())
        {
                String [] y = jTextR.getText().split(" ");
                list = rr.findByEmriMbiemri(y[0], y[1]);
                fillTableR(list);
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Nuk keni selektuar asni opcjon!!!");
        }
    }
    
    public void searchD(String x)
    {
        List<Doktori> list = null;
        
        if(jRadioButtonId.isSelected())
        {
                list = dr.findById(Integer.parseInt(jTextD.getText()));
                fillTableD(list);
        }
        else if(jRadioButtonEmri.isSelected())
        {
                list = dr.findByEmri(jTextD.getText());
                fillTableD(list);
        }
        else if(jRadioButtonMbiemri.isSelected())
        {
                list = dr.findByMbiemri(jTextD.getText());
                fillTableD(list);
        }
        else if(jRadioButtonEmritMbiemrit.isSelected())
        {
                String [] y = jTextD.getText().split(" ");
                list = dr.findByEmriMbiemri(y[0], y[1]);
                fillTableD(list);
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Nuk keni selektuar asni opcjon!!!");
        }
    }
    
    public void searchM(String x)
    {
        List<Motra> list = null;
        
        if(jRadioButtonIdM.isSelected())
        {
                list = ir.findById(Integer.parseInt(jTextM.getText()));
                fillTableM(list);
        }
        else if(jRadioButtonEmriM.isSelected())
        {
                list = ir.findByEmri(jTextM.getText());
                fillTableM(list);
        }
        else if(jRadioButtonMbiemriM.isSelected())
        {
                list = ir.findByMbiemri(jTextM.getText());
                fillTableM(list);
        }
        else if(jRadioButtonEmritMbiemritM.isSelected())
        {
                String [] y = jTextM.getText().split(" ");
                list = ir.findByEmriMbiemri(y[0], y[1]);
                fillTableM(list);
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Nuk keni selektuar asni opcjon!!!");
        }
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if(jTextD.getText() != "")
        {
            searchD(jTextD.getText());
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Nuk keni selektuar asni opcjon!!!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButtonEmriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonEmriActionPerformed
         if(jRadioButtonEmri.isSelected())
        {
            jRadioButtonId.setSelected(false);
            jRadioButtonEmritMbiemrit.setSelected(false);
            jRadioButtonMbiemri.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButtonEmriActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        int x = DoktorijTable.getSelectedRow();
        
        if(x>-1)
        {
            d = dtm.getDoktori(x);
            
            
            EditDritarja ed = new EditDritarja();
            SpitaliGUI.desktopPane.add(ed);
            ed.show();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int r = DoktorijTable.getSelectedRow();
        if(r>-1)
        {
            d = dtm.getDoktori(r);
            System.out.println(d.getId());
            int x = JOptionPane.showConfirmDialog(null, "A jeni i sigurt qe doni te fshini Doktorin?");
            if(x == 0)
            {
                try {
                    dr.remove(d);
                    if(jTextD.getText() != "")
                    {
                        searchD(jTextD.getText());
                    }
                } catch (SpitaliException e) {
                    JOptionPane.showMessageDialog(null, e);
                }
            }
            else if(x == 1)
            {
                JOptionPane.showMessageDialog(null, "Doktori nuk eshte fshir");
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Doktori nuk eshte fshir");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Nuk keni selektuar asni doktor!!!");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(jTextR.getText() != "")
        {
            searchR(jTextR.getText());
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Nuk keni selektuar asni opcjon!!!");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int x = RecepsjonistijTable.getSelectedRow();
        
        if(x>-1)
        {
            r = rtm.getRecepsionisti(x);
            
            EditDritarjaR ed = new EditDritarjaR();
            SpitaliGUI.desktopPane.add(ed);
            ed.show();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        int y = RecepsjonistijTable.getSelectedRow();
        if(y>-1)
        {
            r = rtm.getRecepsionisti(y);
            int x = JOptionPane.showConfirmDialog(null, "A jeni i sigurt qe doni te fshini Doktorin?");
            if(x == 0)
            {
                try {
                    rr.remove(r);
                    if(jTextR.getText() != "")
                    {
                        searchR(jTextR.getText());
                    }
                } catch (SpitaliException e) {
                    JOptionPane.showMessageDialog(null, e);
                }
            }
            else if(x == 1)
            {
                JOptionPane.showMessageDialog(null, "Recepsjonisti nuk eshte fshir");
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Recepsjonisti nuk eshte fshir");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Nuk keni selektuar asni Recepsjonist!!!");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jRadioButtonIdRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonIdRActionPerformed
        if(jRadioButtonIdR.isSelected())
        {
            jRadioButtonEmriR.setSelected(false);
            jRadioButtonEmritMbiemritR.setSelected(false);
            jRadioButtonMbiemriR.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButtonIdRActionPerformed

    private void jRadioButtonEmriRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonEmriRActionPerformed
        if(jRadioButtonEmriR.isSelected())
        {
            jRadioButtonEmritMbiemritR.setSelected(false);
            jRadioButtonMbiemriR.setSelected(false);
            jRadioButtonIdR.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButtonEmriRActionPerformed

    private void jRadioButtonMbiemriRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMbiemriRActionPerformed
        if(jRadioButtonMbiemriR.isSelected())
        {
            jRadioButtonEmriR.setSelected(false);
            jRadioButtonEmritMbiemritR.setSelected(false);
            jRadioButtonIdR.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButtonMbiemriRActionPerformed

    private void jRadioButtonEmritMbiemritRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonEmritMbiemritRActionPerformed
        if(jRadioButtonEmritMbiemritR.isSelected())
        {
            jRadioButtonEmriR.setSelected(false);
            jRadioButtonIdR.setSelected(false);
            jRadioButtonMbiemriR.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButtonEmritMbiemritRActionPerformed

    private void jTextRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextRActionPerformed

    private void jRadioButtonMbiemriMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMbiemriMActionPerformed
        if(jRadioButtonMbiemriM.isSelected())
        {
            jRadioButtonEmriM.setSelected(false);
            jRadioButtonEmritMbiemritM.setSelected(false);
            jRadioButtonIdM.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButtonMbiemriMActionPerformed

    private void jRadioButtonEmritMbiemritMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonEmritMbiemritMActionPerformed
        if(jRadioButtonEmritMbiemritM.isSelected())
        {
            jRadioButtonEmriM.setSelected(false);
            jRadioButtonIdM.setSelected(false);
            jRadioButtonMbiemriM.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButtonEmritMbiemritMActionPerformed

    private void jTextMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextMActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if(jTextM.getText() != "")
        {
            searchM(jTextM.getText());
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Nuk keni selektuar asni opcjon!!!");
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        int x = InfermjerijTable.getSelectedRow();
        
        if(x>-1)
        {
            m = itm.getMotra(x);
            
            EditDritarjaM ed = new EditDritarjaM();
            SpitaliGUI.desktopPane.add(ed);
            ed.show();
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
       int y = InfermjerijTable.getSelectedRow();
        if(y>-1)
        {
            m = itm.getMotra(y);
            int x = JOptionPane.showConfirmDialog(null, "A jeni i sigurt qe doni te fshini Doktorin?");
            if(x == 0)
            {
                try {
                    ir.remove(m);
                    if(jTextM.getText() != "")
                    {
                        searchM(jTextM.getText());
                    }
                } catch (SpitaliException e) {
                    JOptionPane.showMessageDialog(null, e);
                }
            }
            else if(x == 1)
            {
                JOptionPane.showMessageDialog(null, "Infermieri nuk eshte fshir");
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Infermieri nuk eshte fshir");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Nuk keni selektuar asni infermiere!!!");
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jRadioButtonIdMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonIdMActionPerformed
         if(jRadioButtonIdM.isSelected())
        {
            jRadioButtonEmriM.setSelected(false);
            jRadioButtonEmritMbiemritM.setSelected(false);
            jRadioButtonMbiemriM.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButtonIdMActionPerformed

    private void jRadioButtonEmriMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonEmriMActionPerformed
        if(jRadioButtonEmriM.isSelected())
        {
            jRadioButtonEmritMbiemritM.setSelected(false);
            jRadioButtonMbiemriM.setSelected(false);
            jRadioButtonIdM.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButtonEmriMActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable DoktorijTable;
    private javax.swing.JTable InfermjerijTable;
    private javax.swing.JTable RecepsjonistijTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButtonEmri;
    private javax.swing.JRadioButton jRadioButtonEmriM;
    private javax.swing.JRadioButton jRadioButtonEmriR;
    private javax.swing.JRadioButton jRadioButtonEmritMbiemrit;
    private javax.swing.JRadioButton jRadioButtonEmritMbiemritM;
    private javax.swing.JRadioButton jRadioButtonEmritMbiemritR;
    private javax.swing.JRadioButton jRadioButtonId;
    private javax.swing.JRadioButton jRadioButtonIdM;
    private javax.swing.JRadioButton jRadioButtonIdR;
    private javax.swing.JRadioButton jRadioButtonMbiemri;
    private javax.swing.JRadioButton jRadioButtonMbiemriM;
    private javax.swing.JRadioButton jRadioButtonMbiemriR;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextD;
    private javax.swing.JTextField jTextM;
    private javax.swing.JTextField jTextR;
    // End of variables declaration//GEN-END:variables
}
