/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.view;

import BL.DhomaRepository;
import BL.PacientiRepository;
import BL.SpitaliException;
import EJB.Dhoma;
import EJB.Pacienti;
import GUI.model.DhomaTableModel;
import GUI.model.PacientiTableModel;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Arber
 */
public class ShtoPacientinDH extends javax.swing.JInternalFrame {

    private Pacienti p = null;
    private PacientiRepository pr = new PacientiRepository();
    private PacientiTableModel ptm = new PacientiTableModel();
    private DhomaRepository dr = new DhomaRepository();
    private DhomaTableModel dtm = new DhomaTableModel();
    
    public ShtoPacientinDH() {
        initComponents();
        initTebleP();
        intiTablePDhoma(pr.findByDhoma(DhomaMForma.d));
    }

    public void initTebleP()
    {
        List<Pacienti> list = pr.findAll();
        ptm.add(list);
        jTablePacientat.setModel(ptm);
        ptm.fireTableDataChanged();
    }
    
    public void intiTablePDhoma(List<Pacienti> list)
    {
        ptm.add(list);
        jTablePacientetDhom.setModel(ptm);
        ptm.fireTableDataChanged();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePacientat = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablePacientetDhom = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jTablePacientat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTablePacientat);

        jTablePacientetDhom.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTablePacientetDhom);

        jButton1.setText("Shto Pacientin");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Fshij Pacientin");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(16, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(188, 188, 188))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int x = jTablePacientat.getSelectedRow();
        
        if(x>-1)
        {
            if(DhomaMForma.d.getCountP() == DhomaMForma.d.getNrshtratve())
            {
                JOptionPane.showMessageDialog(null, "Dhoma eshte full");
            }
            else{
                p = ptm.getPacienti(x);

                p.setIDdhoma(DhomaMForma.d);

                try {
                    if(pr.update(p))
                    {
                        JOptionPane.showMessageDialog(null, "Eshte shtuar pacjenti ne dhomë");
                        intiTablePDhoma(pr.findByDhoma(DhomaMForma.d));
                    }
                } catch (SpitaliException ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Nuk keni selektuar asni pacient");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int x = jTablePacientetDhom.getSelectedRow();
        
        if(x>-1)
        {
            p = ptm.getPacienti(x);
            
            p.setIDdhoma(null);
            
            int y = JOptionPane.showConfirmDialog(null, "A jeni i sigurt qe doni ta fshini!!!");
            
            if(y == 0)
            {
                try {
                    if(pr.update(p))
                    {
                        JOptionPane.showMessageDialog(null, "Eshte fshir pacient nga dhoma");
                        intiTablePDhoma(pr.findByDhoma(DhomaMForma.d));
                    }
                } catch (SpitaliException ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Nuk eshte fshir asni pacient nga dhoma");
            }
                
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Nuk keni selektuar asni pacient");
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTablePacientat;
    private javax.swing.JTable jTablePacientetDhom;
    // End of variables declaration//GEN-END:variables
}
