/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.view;


import BL.DoktoriRepository;
import BL.FarmacistiRepository;
import BL.InfermieriRepository;
import BL.RescepsionistiRepository;
import BL.SpitaliException;
import EJB.Doktori;
import EJB.Farmacisti;
import EJB.Rescepsionisti;
import EJB.Motra;
import EJB.Sektori;
import javax.swing.JOptionPane;
/**
 *
 * @author Arber
 */
public class ShtoForma extends javax.swing.JInternalFrame {

    /**
     * Creates new form ShtoForma
     */
    
    public ShtoForma() {
        initComponents();
        
        for(int i=1;i<=31;i++)
        {
            ComboBoxDita.addItem(i);
            ComboBoxDitaR.addItem(i);
            ComboBoxDitaM.addItem(i);
            ComboBoxDitaF.addItem(i);
        }
        
        for(int i=1;i<=12;i++)
        {
            ComboBoxMuji.addItem(i);
            ComboBoxMujiR.addItem(i);
            ComboBoxMujiM.addItem(i);
            ComboBoxMujiF.addItem(i);
        }
        
        for(int i=1900;i<=2016;i++)
        {
            ComboBoxViti.addItem(i);
            ComboBoxVitiR.addItem(i);
            ComboBoxVitiM.addItem(i);
            ComboBoxVitiF.addItem(i);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        lShtetiM = new javax.swing.JLabel();
        lEmriM = new javax.swing.JLabel();
        txtShtetiM = new javax.swing.JTextField();
        txtEmriM = new javax.swing.JTextField();
        lQytetiM = new javax.swing.JLabel();
        lMbiemriM = new javax.swing.JLabel();
        lRugaM = new javax.swing.JLabel();
        txtMbiemriM = new javax.swing.JTextField();
        txtQytetiM = new javax.swing.JTextField();
        lGjiniaM = new javax.swing.JLabel();
        txtRugaM = new javax.swing.JTextField();
        RadioButtonMM = new javax.swing.JRadioButton();
        RadioButtonFM = new javax.swing.JRadioButton();
        lNumriShpisM = new javax.swing.JLabel();
        txtNumriShpisM = new javax.swing.JTextField();
        lDataLindjesM = new javax.swing.JLabel();
        ComboBoxDitaM = new javax.swing.JComboBox();
        ComboBoxMujiM = new javax.swing.JComboBox();
        ComboBoxVitiM = new javax.swing.JComboBox();
        lFjalkalimiM = new javax.swing.JLabel();
        txtFjalkalimM = new javax.swing.JPasswordField();
        lDetajetTjeraM = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreaDetajetTjeraM = new javax.swing.JTextArea();
        lSpecializimiM = new javax.swing.JLabel();
        ComboBoxSektoriM = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lShtetiR = new javax.swing.JLabel();
        lEmriR = new javax.swing.JLabel();
        txtShtetiR = new javax.swing.JTextField();
        txtEmriR = new javax.swing.JTextField();
        lQytetiR = new javax.swing.JLabel();
        lMbiemriR = new javax.swing.JLabel();
        lRugaR = new javax.swing.JLabel();
        txtMbiemriR = new javax.swing.JTextField();
        txtQytetiR = new javax.swing.JTextField();
        lGjiniaR = new javax.swing.JLabel();
        txtRugaR = new javax.swing.JTextField();
        RadioButtonMR = new javax.swing.JRadioButton();
        RadioButtonFR = new javax.swing.JRadioButton();
        lNumriShpisR = new javax.swing.JLabel();
        txtNumriShpisR = new javax.swing.JTextField();
        lDataLindjesR = new javax.swing.JLabel();
        ComboBoxDitaR = new javax.swing.JComboBox();
        ComboBoxMujiR = new javax.swing.JComboBox();
        ComboBoxVitiR = new javax.swing.JComboBox();
        lFjalkalimiR = new javax.swing.JLabel();
        txtFjalkalimiR = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        lDetajetTjeraR = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaDetajetTjeraR = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        lEmri = new javax.swing.JLabel();
        txtEmri = new javax.swing.JTextField();
        lMbiemri = new javax.swing.JLabel();
        txtMbiemri = new javax.swing.JTextField();
        lGjinia = new javax.swing.JLabel();
        RadioButtonM = new javax.swing.JRadioButton();
        RadioButtonF = new javax.swing.JRadioButton();
        lDataLindjes = new javax.swing.JLabel();
        ComboBoxDita = new javax.swing.JComboBox();
        ComboBoxMuji = new javax.swing.JComboBox();
        ComboBoxViti = new javax.swing.JComboBox();
        lFjalkalimi = new javax.swing.JLabel();
        txtFjalkalimi = new javax.swing.JPasswordField();
        lSpecializimi = new javax.swing.JLabel();
        txtSpecializimi = new javax.swing.JTextField();
        lDetajetTjera = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaDetajetTjera = new javax.swing.JTextArea();
        BtnRegjistro = new javax.swing.JButton();
        lSpecializimi1 = new javax.swing.JLabel();
        ComboBoxSektori = new javax.swing.JComboBox();
        lShteti = new javax.swing.JLabel();
        txtShteti = new javax.swing.JTextField();
        lQyteti = new javax.swing.JLabel();
        lRuga = new javax.swing.JLabel();
        txtQyteti = new javax.swing.JTextField();
        txtRuga = new javax.swing.JTextField();
        lNumriShpis = new javax.swing.JLabel();
        txtNumriShpis = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lShtetF = new javax.swing.JLabel();
        RadioButtonMF = new javax.swing.JRadioButton();
        lDetajetTjeraF = new javax.swing.JLabel();
        lEmriF = new javax.swing.JLabel();
        RadioButtonFF = new javax.swing.JRadioButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtAreaDetajetTjeraF = new javax.swing.JTextArea();
        txtShtetiF = new javax.swing.JTextField();
        lNumriShpisF = new javax.swing.JLabel();
        txtEmriF = new javax.swing.JTextField();
        txtNumriShpisF = new javax.swing.JTextField();
        lQytetiF = new javax.swing.JLabel();
        lDataLindjesF = new javax.swing.JLabel();
        lMbiemrF = new javax.swing.JLabel();
        ComboBoxDitaF = new javax.swing.JComboBox();
        lRugaF = new javax.swing.JLabel();
        ComboBoxMujiF = new javax.swing.JComboBox();
        txtMbiemriF = new javax.swing.JTextField();
        ComboBoxVitiF = new javax.swing.JComboBox();
        txtQytetiF = new javax.swing.JTextField();
        lFjalkalimiF = new javax.swing.JLabel();
        lGjiniaF = new javax.swing.JLabel();
        txtFjalkalimiF = new javax.swing.JPasswordField();
        txtRugaF = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setClosable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(758, 600));

        lShtetiM.setText("Shteti");

        lEmriM.setText("Emri");

        txtShtetiM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtShtetiMActionPerformed(evt);
            }
        });

        txtEmriM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmriMActionPerformed(evt);
            }
        });

        lQytetiM.setText("Qyteti");

        lMbiemriM.setText("Mbiemri");

        lRugaM.setText("Ruga");

        txtMbiemriM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMbiemriMActionPerformed(evt);
            }
        });

        txtQytetiM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQytetiMActionPerformed(evt);
            }
        });

        lGjiniaM.setText("Gjinia");

        txtRugaM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRugaMActionPerformed(evt);
            }
        });

        RadioButtonMM.setText("M");
        RadioButtonMM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonMMActionPerformed(evt);
            }
        });

        RadioButtonFM.setText("F");
        RadioButtonFM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonFMActionPerformed(evt);
            }
        });

        lNumriShpisM.setText("Nr");

        txtNumriShpisM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumriShpisMActionPerformed(evt);
            }
        });

        lDataLindjesM.setText("Data lindjes");

        ComboBoxDitaM.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dita" }));

        ComboBoxMujiM.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Muaji" }));

        ComboBoxVitiM.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Viti" }));

        lFjalkalimiM.setText("Fjalkalimi");

        txtFjalkalimM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFjalkalimMActionPerformed(evt);
            }
        });

        lDetajetTjeraM.setText("Detajet tjera");

        txtAreaDetajetTjeraM.setColumns(20);
        txtAreaDetajetTjeraM.setRows(5);
        jScrollPane3.setViewportView(txtAreaDetajetTjeraM);

        lSpecializimiM.setText("Sektori");

        ComboBoxSektoriM.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sektori", "1.Kirurgjisë" }));
        ComboBoxSektoriM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxSektoriMActionPerformed(evt);
            }
        });

        jButton2.setText("Regjistro");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lEmriM, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lMbiemriM, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lGjiniaM, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lDataLindjesM, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lShtetiM, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lQytetiM, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lRugaM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lNumriShpisM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(RadioButtonMM)
                                .addGap(18, 18, 18)
                                .addComponent(RadioButtonFM))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(ComboBoxDitaM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ComboBoxMujiM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ComboBoxVitiM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtRugaM, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtQytetiM, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtShtetiM, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtMbiemriM, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtEmriM, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNumriShpisM, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(lFjalkalimiM, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtFjalkalimM, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lDetajetTjeraM, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lSpecializimiM, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ComboBoxSektoriM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton2)))))
                .addContainerGap(463, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lEmriM)
                    .addComponent(txtEmriM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lMbiemriM)
                    .addComponent(txtMbiemriM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lGjiniaM)
                    .addComponent(RadioButtonMM)
                    .addComponent(RadioButtonFM))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lDataLindjesM)
                    .addComponent(ComboBoxDitaM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxMujiM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxVitiM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lShtetiM)
                    .addComponent(txtShtetiM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lQytetiM)
                    .addComponent(txtQytetiM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRugaM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lRugaM))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNumriShpisM)
                    .addComponent(txtNumriShpisM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFjalkalimM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lFjalkalimiM))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBoxSektoriM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lSpecializimiM))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lDetajetTjeraM))
                .addGap(28, 28, 28)
                .addComponent(jButton2)
                .addGap(69, 69, 69))
        );

        jTabbedPane1.addTab("Regjistro Infermierin", jPanel3);

        lShtetiR.setText("Shteti");

        lEmriR.setText("Emri");

        txtShtetiR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtShtetiRActionPerformed(evt);
            }
        });

        txtEmriR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmriRActionPerformed(evt);
            }
        });

        lQytetiR.setText("Qyteti");

        lMbiemriR.setText("Mbiemri");

        lRugaR.setText("Ruga");

        txtMbiemriR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMbiemriRActionPerformed(evt);
            }
        });

        txtQytetiR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQytetiRActionPerformed(evt);
            }
        });

        lGjiniaR.setText("Gjinia");

        txtRugaR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRugaRActionPerformed(evt);
            }
        });

        RadioButtonMR.setText("M");
        RadioButtonMR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonMRActionPerformed(evt);
            }
        });

        RadioButtonFR.setText("F");
        RadioButtonFR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonFRActionPerformed(evt);
            }
        });

        lNumriShpisR.setText("Nr");

        txtNumriShpisR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumriShpisRActionPerformed(evt);
            }
        });

        lDataLindjesR.setText("Data lindjes");

        ComboBoxDitaR.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dita" }));

        ComboBoxMujiR.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Muaji" }));

        ComboBoxVitiR.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Viti" }));

        lFjalkalimiR.setText("Fjalkalimi");

        txtFjalkalimiR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFjalkalimiRActionPerformed(evt);
            }
        });

        jButton1.setText("Regjistro");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lDetajetTjeraR.setText("Detajet tjera");

        txtAreaDetajetTjeraR.setColumns(20);
        txtAreaDetajetTjeraR.setRows(5);
        jScrollPane2.setViewportView(txtAreaDetajetTjeraR);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lFjalkalimiR, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtFjalkalimiR, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lEmriR, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lMbiemriR, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lGjiniaR, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lDataLindjesR, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lShtetiR, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lQytetiR, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lRugaR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lNumriShpisR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(RadioButtonMR)
                                .addGap(18, 18, 18)
                                .addComponent(RadioButtonFR))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(ComboBoxDitaR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ComboBoxMujiR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ComboBoxVitiR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtRugaR, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtQytetiR, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtShtetiR, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtMbiemriR, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtEmriR, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNumriShpisR, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lDetajetTjeraR, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(441, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lEmriR)
                    .addComponent(txtEmriR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lMbiemriR)
                    .addComponent(txtMbiemriR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lGjiniaR)
                    .addComponent(RadioButtonMR)
                    .addComponent(RadioButtonFR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lDataLindjesR)
                    .addComponent(ComboBoxDitaR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxMujiR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxVitiR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lShtetiR)
                    .addComponent(txtShtetiR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lQytetiR)
                    .addComponent(txtQytetiR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRugaR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lRugaR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNumriShpisR)
                    .addComponent(txtNumriShpisR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFjalkalimiR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lFjalkalimiR))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lDetajetTjeraR))
                .addGap(40, 40, 40)
                .addComponent(jButton1)
                .addGap(54, 54, 54))
        );

        jTabbedPane1.addTab("Regjistro Recepsjonistin", jPanel4);

        lEmri.setText("Emri");

        txtEmri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmriActionPerformed(evt);
            }
        });

        lMbiemri.setText("Mbiemri");

        txtMbiemri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMbiemriActionPerformed(evt);
            }
        });

        lGjinia.setText("Gjinia");

        RadioButtonM.setText("M");
        RadioButtonM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonMActionPerformed(evt);
            }
        });

        RadioButtonF.setText("F");
        RadioButtonF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonFActionPerformed(evt);
            }
        });

        lDataLindjes.setText("Data lindjes");

        ComboBoxDita.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dita" }));

        ComboBoxMuji.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Muaji" }));

        ComboBoxViti.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Viti" }));

        lFjalkalimi.setText("Fjalkalimi");

        txtFjalkalimi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFjalkalimiActionPerformed(evt);
            }
        });

        lSpecializimi.setText("Specializimi");

        txtSpecializimi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSpecializimiActionPerformed(evt);
            }
        });

        lDetajetTjera.setText("Detajet tjera");

        txtAreaDetajetTjera.setColumns(20);
        txtAreaDetajetTjera.setRows(5);
        jScrollPane1.setViewportView(txtAreaDetajetTjera);

        BtnRegjistro.setText("Regjistro");
        BtnRegjistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegjistroActionPerformed(evt);
            }
        });

        lSpecializimi1.setText("Sektori");

        ComboBoxSektori.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sektori", "1.Kirurgjisë" }));

        lShteti.setText("Shteti");

        txtShteti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtShtetiActionPerformed(evt);
            }
        });

        lQyteti.setText("Qyteti");

        lRuga.setText("Ruga");

        txtQyteti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQytetiActionPerformed(evt);
            }
        });

        txtRuga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRugaActionPerformed(evt);
            }
        });

        lNumriShpis.setText("Nr");

        txtNumriShpis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumriShpisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lEmri, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lMbiemri, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lGjinia, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lDataLindjes, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lShteti, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lQyteti, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lRuga, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lNumriShpis, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(RadioButtonM)
                                .addGap(18, 18, 18)
                                .addComponent(RadioButtonF))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ComboBoxDita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ComboBoxMuji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ComboBoxViti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtRuga, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtQyteti, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtShteti, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtMbiemri, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                                .addComponent(txtEmri, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                                .addComponent(txtNumriShpis, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lFjalkalimi, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtFjalkalimi, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lDetajetTjera, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lSpecializimi1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lSpecializimi, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ComboBoxSektori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BtnRegjistro)
                                .addComponent(txtSpecializimi)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(491, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lEmri)
                    .addComponent(txtEmri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lMbiemri)
                    .addComponent(txtMbiemri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lGjinia)
                    .addComponent(RadioButtonM)
                    .addComponent(RadioButtonF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lDataLindjes)
                    .addComponent(ComboBoxDita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxMuji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxViti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lShteti)
                    .addComponent(txtShteti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lQyteti)
                    .addComponent(txtQyteti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRuga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lRuga))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNumriShpis)
                    .addComponent(txtNumriShpis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFjalkalimi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lFjalkalimi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSpecializimi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lSpecializimi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBoxSektori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lSpecializimi1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lDetajetTjera))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnRegjistro)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Regjistro  Doktorin", jPanel1);

        lShtetF.setText("Shteti");

        RadioButtonMF.setText("M");
        RadioButtonMF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonMFActionPerformed(evt);
            }
        });

        lDetajetTjeraF.setText("Detajet tjera");

        lEmriF.setText("Emri");

        RadioButtonFF.setText("F");
        RadioButtonFF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonFFActionPerformed(evt);
            }
        });

        txtAreaDetajetTjeraF.setColumns(20);
        txtAreaDetajetTjeraF.setRows(5);
        jScrollPane4.setViewportView(txtAreaDetajetTjeraF);

        txtShtetiF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtShtetiFActionPerformed(evt);
            }
        });

        lNumriShpisF.setText("Nr");

        txtEmriF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmriFActionPerformed(evt);
            }
        });

        txtNumriShpisF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumriShpisFActionPerformed(evt);
            }
        });

        lQytetiF.setText("Qyteti");

        lDataLindjesF.setText("Data lindjes");

        lMbiemrF.setText("Mbiemri");

        ComboBoxDitaF.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dita" }));

        lRugaF.setText("Ruga");

        ComboBoxMujiF.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Muaji" }));

        txtMbiemriF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMbiemriFActionPerformed(evt);
            }
        });

        ComboBoxVitiF.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Viti" }));

        txtQytetiF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQytetiFActionPerformed(evt);
            }
        });

        lFjalkalimiF.setText("Fjalkalimi");

        lGjiniaF.setText("Gjinia");

        txtFjalkalimiF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFjalkalimiFActionPerformed(evt);
            }
        });

        txtRugaF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRugaFActionPerformed(evt);
            }
        });

        jButton3.setText("Regjistro");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lFjalkalimiF, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtFjalkalimiF, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lEmriF, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lMbiemrF, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lGjiniaF, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lDataLindjesF, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lShtetF, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lQytetiF, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lRugaF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lNumriShpisF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(RadioButtonMF)
                                .addGap(18, 18, 18)
                                .addComponent(RadioButtonFF))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(ComboBoxDitaF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ComboBoxMujiF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ComboBoxVitiF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtRugaF, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtQytetiF, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtShtetiF, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtMbiemriF, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtEmriF, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNumriShpisF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lDetajetTjeraF, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(396, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lEmriF)
                    .addComponent(txtEmriF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lMbiemrF)
                    .addComponent(txtMbiemriF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lGjiniaF)
                    .addComponent(RadioButtonMF)
                    .addComponent(RadioButtonFF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lDataLindjesF)
                    .addComponent(ComboBoxDitaF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxMujiF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxVitiF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lShtetF)
                    .addComponent(txtShtetiF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lQytetiF)
                    .addComponent(txtQytetiF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRugaF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lRugaF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNumriShpisF)
                    .addComponent(txtNumriShpisF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFjalkalimiF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lFjalkalimiF))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lDetajetTjeraF))
                .addGap(47, 47, 47)
                .addComponent(jButton3)
                .addGap(64, 64, 64))
        );

        jTabbedPane1.addTab("Regjistro Farmacistin", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 916, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        setBounds(0, 0, 942, 600);
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmriActionPerformed

    private void txtMbiemriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMbiemriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMbiemriActionPerformed

    private void RadioButtonMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonMActionPerformed
        // TODO add your handling code here:
        if(RadioButtonM.isSelected()){
            RadioButtonF.setSelected(false);
        }
    }//GEN-LAST:event_RadioButtonMActionPerformed

    private void RadioButtonFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonFActionPerformed
        if(RadioButtonF.isSelected()){
            RadioButtonM.setSelected(false);
        }
    }//GEN-LAST:event_RadioButtonFActionPerformed

    private void txtFjalkalimiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFjalkalimiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFjalkalimiActionPerformed

    private void txtSpecializimiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSpecializimiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSpecializimiActionPerformed
    
    private void BtnRegjistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegjistroActionPerformed
        try
        {
            DoktoriRepository dr = new DoktoriRepository();
            
            Doktori d = new Doktori();
            d.setEmri(txtEmri.getText());
            java.sql.Date dl = java.sql.Date.valueOf( ComboBoxViti.getSelectedItem().toString()+"-"+ComboBoxMuji.getSelectedItem().toString()+"-"+ComboBoxDita.getSelectedItem().toString() ); //"1995-12-30"
            d.setDataLindjes(dl);
            d.setDetajetTjera(txtAreaDetajetTjera.getText());
            d.setFjalkalimi(txtFjalkalimi.getText());
            d.setMbiemri(txtMbiemri.getText());
            d.setSpecializimi(txtSpecializimi.getText());
            d.setQyteti(txtQyteti.getText());
            d.setShteti(txtShteti.getText());
            d.setRuga(txtRuga.getText());
            d.setNumri(Integer.parseInt(txtNumriShpis.getText()));
            
            //Sektori
            String x = ComboBoxSektori.getSelectedItem().toString();
            String [] y = x.split("\\.");
            Sektori s = new Sektori();
            s.setEmri(y[1]);
            s.setId(Integer.parseInt(y[0]));
            d.setSektoriID(s);
            
            if(RadioButtonM.isSelected()){
                d.setGjinia('M');
            }
            
            if(RadioButtonF.isSelected()){
                d.setGjinia('F');
            }
            
            if(dr.insert(d));
            {
                JOptionPane.showMessageDialog(null, "Eshte regjistruar Doktori!!!");
            }
            
        }catch(SpitaliException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_BtnRegjistroActionPerformed

    private void txtShtetiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtShtetiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtShtetiActionPerformed

    private void txtQytetiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQytetiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQytetiActionPerformed

    private void txtRugaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRugaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRugaActionPerformed

    private void txtNumriShpisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumriShpisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumriShpisActionPerformed

    private void txtShtetiRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtShtetiRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtShtetiRActionPerformed

    private void txtEmriRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmriRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmriRActionPerformed

    private void txtMbiemriRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMbiemriRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMbiemriRActionPerformed

    private void txtQytetiRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQytetiRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQytetiRActionPerformed

    private void txtRugaRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRugaRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRugaRActionPerformed

    private void RadioButtonMRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonMRActionPerformed
        if(RadioButtonMR.isSelected())
        {
            RadioButtonFR.setSelected(false);
        }
    }//GEN-LAST:event_RadioButtonMRActionPerformed

    private void RadioButtonFRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonFRActionPerformed
        if(RadioButtonFR.isSelected())
        {
            RadioButtonMR.setSelected(false);
        }
    }//GEN-LAST:event_RadioButtonFRActionPerformed

    private void txtNumriShpisRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumriShpisRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumriShpisRActionPerformed

    private void txtFjalkalimiRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFjalkalimiRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFjalkalimiRActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try
        {
            RescepsionistiRepository rr = new RescepsionistiRepository();
            
            Rescepsionisti r = new Rescepsionisti();
            r.setEmri(txtEmriR.getText());
            java.sql.Date dl = java.sql.Date.valueOf( ComboBoxVitiR.getSelectedItem().toString()+"-"+ComboBoxMujiR.getSelectedItem().toString()+"-"+ComboBoxDitaR.getSelectedItem().toString() ); //"1995-12-30"
            r.setDataLindjes(dl);
            r.setDetajettjera(txtAreaDetajetTjeraR.getText());
            r.setFjalkalimi(txtFjalkalimiR.getText());
            r.setMbiemri(txtMbiemriR.getText());
            r.setQyteti(txtQytetiR.getText());
            r.setShteti(txtShtetiR.getText());
            r.setRuga(txtRugaR.getText());
            r.setNumri(Integer.parseInt(txtNumriShpisR.getText()));
            
            if(RadioButtonMR.isSelected()){
                r.setGjinia('M');
            }
            
            if(RadioButtonFR.isSelected()){
                r.setGjinia('F');
            }
            
            if(rr.insert(r));
            {
                JOptionPane.showMessageDialog(null, "Eshte regjistruar Recepsjonisti!!!");
            }
            
        }catch(SpitaliException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtShtetiMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtShtetiMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtShtetiMActionPerformed

    private void txtEmriMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmriMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmriMActionPerformed

    private void txtMbiemriMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMbiemriMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMbiemriMActionPerformed

    private void txtQytetiMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQytetiMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQytetiMActionPerformed

    private void txtRugaMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRugaMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRugaMActionPerformed

    private void RadioButtonMMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonMMActionPerformed
        if(RadioButtonMM.isSelected())
        {
            RadioButtonFM.setSelected(false);
        }
    }//GEN-LAST:event_RadioButtonMMActionPerformed

    private void RadioButtonFMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonFMActionPerformed
        if(RadioButtonFM.isSelected())
        {
            RadioButtonMM.setSelected(false);
        }
    }//GEN-LAST:event_RadioButtonFMActionPerformed

    private void txtNumriShpisMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumriShpisMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumriShpisMActionPerformed

    private void txtFjalkalimMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFjalkalimMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFjalkalimMActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try
        {
            InfermieriRepository ir = new InfermieriRepository();
            
            Motra m = new Motra();
            m.setEmri(txtEmriM.getText());
            java.sql.Date dl = java.sql.Date.valueOf( ComboBoxVitiM.getSelectedItem().toString()+"-"+ComboBoxMujiM.getSelectedItem().toString()+"-"+ComboBoxDitaM.getSelectedItem().toString() ); //"1995-12-30"
            m.setDataLindjes(dl);
            m.setDetajettjera(txtAreaDetajetTjeraM.getText());
            m.setFjalkalimi(txtFjalkalimM.getText());
            m.setMbiemri(txtMbiemriM.getText());
            m.setQyteti(txtQytetiM.getText());
            m.setShteti(txtShtetiM.getText());
            m.setRuga(txtRugaM.getText());
            m.setNumri(Integer.parseInt(txtNumriShpisM.getText()));
            
            
            //Sektori
            String x = ComboBoxSektoriM.getSelectedItem().toString();
            String [] y = x.split("\\.");
            Sektori s = new Sektori();
            s.setEmri(y[1]);
            s.setId(Integer.parseInt(y[0]));
            m.setSektoriID(s);
            
            if(RadioButtonMM.isSelected()){
                m.setGjinia('M');
            }
            
            if(RadioButtonFM.isSelected()){
                m.setGjinia('F');
            }
            
            if(ir.insert(m));
            {
                JOptionPane.showMessageDialog(null, "Eshte regjistruar Infermieri!!!");
            }
            
        }catch(SpitaliException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void RadioButtonMFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonMFActionPerformed
        if(RadioButtonMF.isSelected())
        {
            RadioButtonFF.setSelected(false);
        }
    }//GEN-LAST:event_RadioButtonMFActionPerformed

    private void RadioButtonFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonFFActionPerformed
        if(RadioButtonFF.isSelected())
        {
            RadioButtonMF.setSelected(false);
        }
    }//GEN-LAST:event_RadioButtonFFActionPerformed

    private void txtShtetiFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtShtetiFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtShtetiFActionPerformed

    private void txtEmriFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmriFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmriFActionPerformed

    private void txtNumriShpisFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumriShpisFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumriShpisFActionPerformed

    private void txtMbiemriFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMbiemriFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMbiemriFActionPerformed

    private void txtQytetiFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQytetiFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQytetiFActionPerformed

    private void txtFjalkalimiFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFjalkalimiFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFjalkalimiFActionPerformed

    private void txtRugaFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRugaFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRugaFActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try
        {
            FarmacistiRepository fr = new FarmacistiRepository();
            
            Farmacisti f = new Farmacisti();
            f.setEmri(txtEmriF.getText());
            java.sql.Date dl = java.sql.Date.valueOf( ComboBoxVitiF.getSelectedItem().toString()+"-"+ComboBoxMujiF.getSelectedItem().toString()+"-"+ComboBoxDitaF.getSelectedItem().toString() ); //"1995-12-30"
            f.setDataLindjes(dl);
            f.setDetajetTjera(txtAreaDetajetTjeraF.getText());
            f.setFjalkalimi(txtFjalkalimiF.getText());
            f.setMbiemri(txtMbiemriF.getText());
            f.setQyteti(txtQytetiF.getText());
            f.setShteti(txtShtetiF.getText());
            f.setRuga(txtRugaF.getText());
            f.setNumri(Integer.parseInt(txtNumriShpisF.getText()));
            
            if(RadioButtonMF.isSelected()){
                f.setGjinia('M');
            }
            
            if(RadioButtonFF.isSelected()){
                f.setGjinia('F');
            }
            
            if(fr.insert(f));
            {
                JOptionPane.showMessageDialog(null, "Eshte regjistruar Farmacisti!!!");
            }
            
        }catch(SpitaliException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void ComboBoxSektoriMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxSektoriMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxSektoriMActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnRegjistro;
    private javax.swing.JComboBox ComboBoxDita;
    private javax.swing.JComboBox ComboBoxDitaF;
    private javax.swing.JComboBox ComboBoxDitaM;
    private javax.swing.JComboBox ComboBoxDitaR;
    private javax.swing.JComboBox ComboBoxMuji;
    private javax.swing.JComboBox ComboBoxMujiF;
    private javax.swing.JComboBox ComboBoxMujiM;
    private javax.swing.JComboBox ComboBoxMujiR;
    private javax.swing.JComboBox ComboBoxSektori;
    private javax.swing.JComboBox ComboBoxSektoriM;
    private javax.swing.JComboBox ComboBoxViti;
    private javax.swing.JComboBox ComboBoxVitiF;
    private javax.swing.JComboBox ComboBoxVitiM;
    private javax.swing.JComboBox ComboBoxVitiR;
    private javax.swing.JRadioButton RadioButtonF;
    private javax.swing.JRadioButton RadioButtonFF;
    private javax.swing.JRadioButton RadioButtonFM;
    private javax.swing.JRadioButton RadioButtonFR;
    private javax.swing.JRadioButton RadioButtonM;
    private javax.swing.JRadioButton RadioButtonMF;
    private javax.swing.JRadioButton RadioButtonMM;
    private javax.swing.JRadioButton RadioButtonMR;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lDataLindjes;
    private javax.swing.JLabel lDataLindjesF;
    private javax.swing.JLabel lDataLindjesM;
    private javax.swing.JLabel lDataLindjesR;
    private javax.swing.JLabel lDetajetTjera;
    private javax.swing.JLabel lDetajetTjeraF;
    private javax.swing.JLabel lDetajetTjeraM;
    private javax.swing.JLabel lDetajetTjeraR;
    private javax.swing.JLabel lEmri;
    private javax.swing.JLabel lEmriF;
    private javax.swing.JLabel lEmriM;
    private javax.swing.JLabel lEmriR;
    private javax.swing.JLabel lFjalkalimi;
    private javax.swing.JLabel lFjalkalimiF;
    private javax.swing.JLabel lFjalkalimiM;
    private javax.swing.JLabel lFjalkalimiR;
    private javax.swing.JLabel lGjinia;
    private javax.swing.JLabel lGjiniaF;
    private javax.swing.JLabel lGjiniaM;
    private javax.swing.JLabel lGjiniaR;
    private javax.swing.JLabel lMbiemrF;
    private javax.swing.JLabel lMbiemri;
    private javax.swing.JLabel lMbiemriM;
    private javax.swing.JLabel lMbiemriR;
    private javax.swing.JLabel lNumriShpis;
    private javax.swing.JLabel lNumriShpisF;
    private javax.swing.JLabel lNumriShpisM;
    private javax.swing.JLabel lNumriShpisR;
    private javax.swing.JLabel lQyteti;
    private javax.swing.JLabel lQytetiF;
    private javax.swing.JLabel lQytetiM;
    private javax.swing.JLabel lQytetiR;
    private javax.swing.JLabel lRuga;
    private javax.swing.JLabel lRugaF;
    private javax.swing.JLabel lRugaM;
    private javax.swing.JLabel lRugaR;
    private javax.swing.JLabel lShtetF;
    private javax.swing.JLabel lShteti;
    private javax.swing.JLabel lShtetiM;
    private javax.swing.JLabel lShtetiR;
    private javax.swing.JLabel lSpecializimi;
    private javax.swing.JLabel lSpecializimi1;
    private javax.swing.JLabel lSpecializimiM;
    private javax.swing.JTextArea txtAreaDetajetTjera;
    private javax.swing.JTextArea txtAreaDetajetTjeraF;
    private javax.swing.JTextArea txtAreaDetajetTjeraM;
    private javax.swing.JTextArea txtAreaDetajetTjeraR;
    private javax.swing.JTextField txtEmri;
    private javax.swing.JTextField txtEmriF;
    private javax.swing.JTextField txtEmriM;
    private javax.swing.JTextField txtEmriR;
    private javax.swing.JPasswordField txtFjalkalimM;
    private javax.swing.JPasswordField txtFjalkalimi;
    private javax.swing.JPasswordField txtFjalkalimiF;
    private javax.swing.JPasswordField txtFjalkalimiR;
    private javax.swing.JTextField txtMbiemri;
    private javax.swing.JTextField txtMbiemriF;
    private javax.swing.JTextField txtMbiemriM;
    private javax.swing.JTextField txtMbiemriR;
    private javax.swing.JTextField txtNumriShpis;
    private javax.swing.JTextField txtNumriShpisF;
    private javax.swing.JTextField txtNumriShpisM;
    private javax.swing.JTextField txtNumriShpisR;
    private javax.swing.JTextField txtQyteti;
    private javax.swing.JTextField txtQytetiF;
    private javax.swing.JTextField txtQytetiM;
    private javax.swing.JTextField txtQytetiR;
    private javax.swing.JTextField txtRuga;
    private javax.swing.JTextField txtRugaF;
    private javax.swing.JTextField txtRugaM;
    private javax.swing.JTextField txtRugaR;
    private javax.swing.JTextField txtShteti;
    private javax.swing.JTextField txtShtetiF;
    private javax.swing.JTextField txtShtetiM;
    private javax.swing.JTextField txtShtetiR;
    private javax.swing.JTextField txtSpecializimi;
    // End of variables declaration//GEN-END:variables
}
